[package]
name = "n64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.ctrlc]
version = "3.4.1"

[dependencies.rustyline]
version = "12.0.0"

