[package]
name = "n64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-core = "0.1.32"

[dependencies.ctrlc]
version = "3.4.1"

[dependencies.rustyline]
version = "12.0.0"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"

